from __future__ import annotations

from typing import Protocol
from app.domain.account import Account


class AccountRepository(Protocol):
    def list_accounts(self) -> list[Account]: ...
    def get_account(self, account_id: str) -> Account: ...
    def add(self, account: Account) -> None: ...
    def delete(self, *, account_id: str) -> bool: ...