from __future__ import annotations

from typing import Protocol
from app.domain.account import Account


class AccountRepository(Protocol):
    def list_accounts(self, *, profile_id: str | None = None) -> list[Account]: ...
    def get_account(self, account_id: str, *, profile_id: str | None = None) -> Account: ...
    def add(self, account: Account, *, profile_id: str | None = None) -> None: ...
    def delete(self, *, account_id: str) -> bool: ...