from __future__ import annotations
from typing import Protocol

from app.domain.instrument import Instrument


class InstrumentRepository(Protocol):
    def list(self) -> list[Instrument]: ...
    def get(self, symbol: str) -> Instrument: ...
    def add(self, instrument: Instrument) -> None: ...
    def delete(self, *, symbol: str) -> bool: ...