from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.portfolio import Portfolio, PortfolioType


class PortfolioRepository(Protocol):
    def list(self, *, profile_id: str | None = None) -> list[Portfolio]: ...
    def get(self, portfolio_id: UUID, *, profile_id: str | None = None) -> Portfolio: ...
    def add(self, portfolio: Portfolio, *, profile_id: str | None = None) -> None: ...
    def delete(self, *, portfolio_id: UUID, profile_id: str | None = None) -> bool: ...
    def update(self, *, portfolio_id: UUID, name: str | None = None, portfolio_type: PortfolioType | None = None, profile_id: str | None = None) -> Portfolio: ...