from __future__ import annotations

import datetime as dt
from typing import Protocol
from uuid import UUID

from app.domain.portfolio import PortfolioSnapshot


class PortfolioSnapshotRepository(Protocol):
    def add(self, snapshot: PortfolioSnapshot, *, profile_id: str | None = None) -> None: ...
    def list(self, portfolio_id: UUID | None = None, *, profile_id: str | None = None) -> list[PortfolioSnapshot]: ...
    def list_between(self, *, portfolio_id: UUID, date_from: dt.date, date_to: dt.date, profile_id: str | None = None) -> list[PortfolioSnapshot]: ...
    def delete_all(self, *, portfolio_id: UUID, profile_id: str | None = None) -> int: ...
    def delete_from(self, *, portfolio_id: UUID, from_date: dt.date, profile_id: str | None = None) -> int: ...