from __future__ import annotations

import datetime as dt
from typing import Protocol

from app.domain.price_point import PricePoint


class PriceRepository(Protocol):
    def add(self, price: PricePoint) -> None: ...
    def list(self, *, symbol: str | None = None) -> list[PricePoint]: ...
    def list_between(self, *, symbol: str, date_from: dt.date, date_to: dt.date) -> list[PricePoint]: ...
    def latest(self, *, symbol: str) -> PricePoint | None: ...
