from __future__ import annotations

from typing import Protocol

from app.domain.profile import Profile


class ProfileRepository(Protocol):
    def list_profiles(self, *, workspace_id: str) -> list[Profile]: ...
    def get_profile(self, *, profile_id: str) -> Profile: ...
    def create_profile(self, *, workspace_id: str, display_name: str) -> Profile: ...
    def delete_profile(self, *, profile_id: str) -> bool: ...