from __future__ import annotations

from typing import Protocol

from app.domain.profile import Profile


class ProfileRepository(Protocol):
    def list_profiles(self, *, workspace_id: str) -> list[Profile]: ...
    def get_profile(self, *, profile_id: str) -> Profile: ...
    def create_profile(self, *, workspace_id: str, display_name: str) -> Profile: ...
    def delete_profile(self, *, profile_id: str) -> bool: ...
    def grant_profile_access(self, *, user_id: str, profile_id: str, permission: str = "OWNER") -> None: ...
    def has_profile_access(self, *, user_id: str, profile_id: str) -> bool: ...
    def get_default_profile_id_for_user(self, user_id: str) -> str | None: ...
    def list_profiles_for_user(self, user_id: str) -> list[Profile]: ...
    def revoke_workspace_access(self, *, user_id: str, workspace_id: str) -> None: ...
    def get_profile_permission(self, *, user_id: str, profile_id: str) -> str | None: ...
    def update_workspace_permissions(self, *, user_id: str, workspace_id: str, permission: str) -> None: ...