from __future__ import annotations
import datetime as dt
from typing import Protocol
from uuid import UUID

from app.domain.trade import Trade


class TradeRepository(Protocol):
    def add(self, trade: Trade, *, profile_id: str | None = None) -> None: ...
    def list(self, *, portfolio_id: UUID | None = None, profile_id: str | None = None) -> list[Trade]: ...
    def list_between(self, *, portfolio_id: UUID, date_from: dt.date, date_to: dt.date, profile_id: str | None = None) -> list[Trade]: ...
    def update(self, *, trade_id: UUID, patch: dict, profile_id: str | None = None) -> Trade: ...
    def delete(self, *, trade_id: UUID, profile_id: str | None = None) -> bool: ...
    def get(self, trade_id: UUID, *, profile_id: str | None = None) -> Trade: ...