from __future__ import annotations

from typing import Protocol

from app.domain.user import User


class UserRepository(Protocol):
    def get(self, user_id: str) -> User: ...
    def get_by_email(self, email: str) -> User | None: ...
    def create(self, *, email: str, password_hash: str) -> User: ...
    def get_password_hash(self, user_id: str) -> str: ...
