from __future__ import annotations

from typing import Protocol

from app.domain.workspace import Workspace


class WorkspaceRepository(Protocol):
    def list_workspaces(self) -> list[Workspace]: ...
    def list_workspaces_for_user(self, user_id: str) -> list[Workspace]: ...
    def get_workspace(self, *, workspace_id: str) -> Workspace: ...
    def create_workspace(self, *, name: str) -> Workspace: ...
    def has_workspace_membership(self, *, user_id: str, workspace_id: str) -> bool: ...
    def add_workspace_membership(self, *, user_id: str, workspace_id: str, role: str) -> None: ...