from __future__ import annotations

from typing import Protocol

from app.domain.workspace import Workspace


class WorkspaceMember:
    __slots__ = ("user_id", "email", "role")

    def __init__(self, user_id: str, email: str, role: str) -> None:
        self.user_id = user_id
        self.email = email
        self.role = role


class WorkspaceRepository(Protocol):
    def list_workspaces(self) -> list[Workspace]: ...
    def list_workspaces_for_user(self, user_id: str) -> list[Workspace]: ...
    def get_workspace(self, *, workspace_id: str) -> Workspace: ...
    def create_workspace(self, *, name: str) -> Workspace: ...
    def has_workspace_membership(self, *, user_id: str, workspace_id: str) -> bool: ...
    def add_workspace_membership(self, *, user_id: str, workspace_id: str, role: str) -> None: ...
    def get_membership_role(self, *, user_id: str, workspace_id: str) -> str | None: ...
    def list_members(self, workspace_id: str) -> list[WorkspaceMember]: ...
    def remove_member(self, *, user_id: str, workspace_id: str) -> None: ...
    def count_owners(self, workspace_id: str) -> int: ...
    def update_membership_role(self, *, user_id: str, workspace_id: str, new_role: str) -> None: ...
