"""check drift

Revision ID: 2450510e8417
Revises: 2577ac0ec754
Create Date: 2026-02-18 16:18:02.053104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2450510e8417'
down_revision: Union[str, Sequence[str], None] = '2577ac0ec754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'display_name', name='uq_profiles_workspace_display_name')
    )
    op.create_index(op.f('ix_profiles_workspace_id'), 'profiles', ['workspace_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('profile_access',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'user_id')
    )

    DEFAULT_USER_ID = "00000000-0000-0000-0000-000000000001"
    DEFAULT_WORKSPACE_ID = "00000000-0000-0000-0000-000000000002"
    DEFAULT_PROFILE_ID = "00000000-0000-0000-0000-000000000003"

    # Seed default identity objects (single-user bootstrap)
    bind = op.get_bind()

    bind.execute(
        sa.text(
            "INSERT INTO users (id, email, password_hash, is_disabled) "
            "VALUES (:id, :email, :ph, false) "
            "ON CONFLICT (id) DO NOTHING"
        ),
        {"id": DEFAULT_USER_ID, "email": "local@dashmoney", "ph": "DISABLED_UNTIL_AUTH"},
    )

    bind.execute(
        sa.text(
            "INSERT INTO workspaces (id, name) "
            "VALUES (:id, :name) "
            "ON CONFLICT (id) DO NOTHING"
        ),
        {"id": DEFAULT_WORKSPACE_ID, "name": "Default"},
    )

    bind.execute(
        sa.text(
            "INSERT INTO profiles (id, workspace_id, display_name) "
            "VALUES (:id, :wid, :name) "
            "ON CONFLICT (id) DO NOTHING"
        ),
        {"id": DEFAULT_PROFILE_ID, "wid": DEFAULT_WORKSPACE_ID, "name": "Default"},
    )

    bind.execute(
        sa.text(
            "INSERT INTO workspace_memberships (workspace_id, user_id, role) "
            "VALUES (:wid, :uid, :role) "
            "ON CONFLICT DO NOTHING"
        ),
        {"wid": DEFAULT_WORKSPACE_ID, "uid": DEFAULT_USER_ID, "role": "OWNER"},
    )

    bind.execute(
        sa.text(
            "INSERT INTO profile_access (profile_id, user_id, permission) "
            "VALUES (:pid, :uid, :perm) "
            "ON CONFLICT DO NOTHING"
        ),
        {"pid": DEFAULT_PROFILE_ID, "uid": DEFAULT_USER_ID, "perm": "OWNER"},
    )

    

    op.add_column('accounts', sa.Column('profile_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_accounts_profile_id'), 'accounts', ['profile_id'], unique=False)
    op.create_foreign_key(
        "fk_accounts_profile_id_profiles",
        "accounts", "profiles",
        ["profile_id"], ["id"],
        ondelete="RESTRICT",
    )
    op.add_column('portfolio_snapshots', sa.Column('profile_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_portfolio_snapshots_profile_id'), 'portfolio_snapshots', ['profile_id'], unique=False)
    op.create_foreign_key(
        "fk_portfolio_snapshots_profile_id_profiles",
        "portfolio_snapshots", "profiles",
        ["profile_id"], ["id"],
        ondelete="CASCADE",
    )
    op.add_column('portfolios', sa.Column('profile_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_portfolios_profile_id'), 'portfolios', ['profile_id'], unique=False)
    op.create_foreign_key(
        "fk_portfolios_profile_id_profiles",
        "portfolios", "profiles",
        ["profile_id"], ["id"],
        ondelete="RESTRICT",
    )
    op.add_column('trades', sa.Column('profile_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_trades_profile_id'), 'trades', ['profile_id'], unique=False)
    op.create_foreign_key(
        "fk_trades_profile_id_profiles",
        "trades", "profiles",
        ["profile_id"], ["id"],
        ondelete="CASCADE",
    )
    op.add_column('transactions', sa.Column('profile_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_transactions_profile_id'), 'transactions', ['profile_id'], unique=False)
    op.create_foreign_key(
        "fk_transactions_profile_id_profiles",
        "transactions", "profiles",
        ["profile_id"], ["id"],
        ondelete="RESTRICT",
    )
    # Backfill existing rows (now that columns exist)
    bind.execute(sa.text("UPDATE accounts SET profile_id = :pid WHERE profile_id IS NULL"), {"pid": DEFAULT_PROFILE_ID})
    bind.execute(sa.text("UPDATE transactions SET profile_id = :pid WHERE profile_id IS NULL"), {"pid": DEFAULT_PROFILE_ID})
    bind.execute(sa.text("UPDATE portfolios SET profile_id = :pid WHERE profile_id IS NULL"), {"pid": DEFAULT_PROFILE_ID})
    bind.execute(sa.text("UPDATE trades SET profile_id = :pid WHERE profile_id IS NULL"), {"pid": DEFAULT_PROFILE_ID})
    bind.execute(sa.text("UPDATE portfolio_snapshots SET profile_id = :pid WHERE profile_id IS NULL"), {"pid": DEFAULT_PROFILE_ID})


    # ### end Alembic commands ###

    op.alter_column("accounts", "profile_id", existing_type=sa.String(length=36), nullable=False)
    op.alter_column("transactions", "profile_id", existing_type=sa.String(length=36), nullable=False)
    op.alter_column("portfolios", "profile_id", existing_type=sa.String(length=36), nullable=False)
    op.alter_column("trades", "profile_id", existing_type=sa.String(length=36), nullable=False)
    op.alter_column("portfolio_snapshots", "profile_id", existing_type=sa.String(length=36), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_transactions_profile_id_profiles", "transactions", type_="foreignkey")
    op.drop_index(op.f('ix_transactions_profile_id'), table_name='transactions')
    op.drop_column('transactions', 'profile_id')

    op.drop_constraint("fk_trades_profile_id_profiles", "trades", type_="foreignkey")
    op.drop_index(op.f('ix_trades_profile_id'), table_name='trades')
    op.drop_column('trades', 'profile_id')

    op.drop_constraint("fk_portfolios_profile_id_profiles", "portfolios", type_="foreignkey")
    op.drop_index(op.f('ix_portfolios_profile_id'), table_name='portfolios')
    op.drop_column('portfolios', 'profile_id')

    op.drop_constraint("fk_portfolio_snapshots_profile_id_profiles", "portfolio_snapshots", type_="foreignkey")
    op.drop_index(op.f('ix_portfolio_snapshots_profile_id'), table_name='portfolio_snapshots')
    op.drop_column('portfolio_snapshots', 'profile_id')

    op.drop_constraint("fk_accounts_profile_id_profiles", "accounts", type_="foreignkey")
    op.drop_index(op.f('ix_accounts_profile_id'), table_name='accounts')
    op.drop_column('accounts', 'profile_id')

    op.drop_table('profile_access')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_profiles_workspace_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
