"""add fks for portfolio snapshots prices trades

Revision ID: 2577ac0ec754
Revises: 6abfefc26f8b
Create Date: 2026-02-18 15:02:57.622064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2577ac0ec754'
down_revision: Union[str, Sequence[str], None] = '6abfefc26f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_portfolio_snapshots_portfolio_id_portfolios",
        "portfolio_snapshots",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        "fk_portfolios_cash_account_id_accounts",
        "portfolios",
        "accounts",
        ["cash_account_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.create_foreign_key(
        "fk_price_points_symbol_instruments",
        "price_points",
        "instruments",
        ["symbol"],
        ["symbol"],
        ondelete="RESTRICT",
    )

    op.create_foreign_key(
        "fk_trades_instrument_symbol_instruments",
        "trades",
        "instruments",
        ["instrument_symbol"],
        ["symbol"],
        ondelete="RESTRICT",
    )

    op.create_foreign_key(
        "fk_trades_portfolio_id_portfolios",
        "trades",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.create_foreign_key(
        "fk_trades_linked_cash_tx_id_transactions",
        "trades",
        "transactions",
        ["linked_cash_tx_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_trades_linked_cash_tx_id_transactions", "trades", type_="foreignkey")
    op.drop_constraint("fk_trades_portfolio_id_portfolios", "trades", type_="foreignkey")
    op.drop_constraint("fk_trades_instrument_symbol_instruments", "trades", type_="foreignkey")
    op.drop_constraint("fk_price_points_symbol_instruments", "price_points", type_="foreignkey")
    op.drop_constraint("fk_portfolios_cash_account_id_accounts", "portfolios", type_="foreignkey")
    op.drop_constraint("fk_portfolio_snapshots_portfolio_id_portfolios", "portfolio_snapshots", type_="foreignkey")

    # ### end Alembic commands ###
