"""add fk and unique constraint to transactions

Revision ID: 6abfefc26f8b
Revises: 0852d4bc0486
Create Date: 2026-02-18 14:46:12.781734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6abfefc26f8b'
down_revision: Union[str, Sequence[str], None] = '0852d4bc0486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tx_account_date_seq', 'transactions', ['account_id', 'date', 'sequence'])
    op.create_foreign_key(
        "fk_transactions_account_id_accounts",
        "transactions",
        "accounts",
        ["account_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_transactions_account_id_accounts", "transactions", type_="foreignkey")

    op.drop_constraint('uq_tx_account_date_seq', 'transactions', type_='unique')
    # ### end Alembic commands ###
